---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  namespace: demo
  labels:
    app: helloworld
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.k8s-demo: semver:~1.0.0
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: k8s-demo
        image: anuroopaich/k8s-demo:1.0.2
        ports:
        - name: nodejs-port
          containerPort: 3000
