apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  namespace: demo
spec:
  ports:
  - port: 80
    targetPort: nodejs-port
    protocol: TCP
  selector:
    app: helloworld
  type: NodePort
